name: Log Supabase Branch Info

on:
  push:
    branches: [main, add_color]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  log-supabase-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Log Supabase branch info
        run: |
          echo "Checking for Supabase branch information..."

          # Check if supabase directory exists
          if [ -d "supabase" ]; then
            echo "Supabase directory found"

            # Try to get branch info if logged in
            if supabase branches list --experimental 2>/dev/null; then
              echo "Branch list retrieved successfully"
            else
              echo "Unable to retrieve branch list - may need authentication"
            fi
          else
            echo "No supabase directory found in repository"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
